Benchmark:
  Total: 5000000
  Concurrency: 0
  PayloadSize: 128
  ConsumeTimeoutSeconds: 900
  ProgressIntervalSeconds: 5
  EnvironmentSuffix: Perf

ConnectionStrings:
  mysql: server=localhost;database=eventbus_perf;user id=root;password=123123;Pooling=True;Minimum Pool Size=20;Maximum Pool Size=100;AllowUserVariables=true;UseAffectedRows=false
  postgresql: Host=localhost;Port=5433;Database=eventbus_perf_pg2;Username=pguser;Password=123123;Pooling=true;Maximum Pool Size=100
  mongodb:  mongodb://root:123123@localhost:27017/?authSource=admin

EventBus:
  Kafka:
    Properties:
      "bootstrap.servers": "localhost"
      "allow.auto.create.topics": "true"
      "linger.ms": "5"
      "batch.size": "65536"
      "compression.type": "lz4"
  RabbitMQ:
    Host: localhost
    UserName: rabbit
    Password: "123123"
    Port: 55672
  Redis:
    Connection: 127.0.0.1:6379,defaultDatabase=1
  Pulsar:
    ServiceUrl: "pulsar://localhost"

Logging:
  LogLevel:
    Default: Warning
    Microsoft: Warning
    Shashlik.EventBus: Warning
    Sample.Performance: Information
