name: test

on:
  push:
    branches: [ test ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: 123123
          MYSQL_DATABASE: test
          MYSQL_USER: testuser
          MYSQL_PASSWORD: 123123
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -p123123"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

      rabbitmq:
        image: rabbitmq
        env:
          RABBITMQ_DEFAULT_USER: rabbittest
          RABBITMQ_DEFAULT_PASS: rabbittest
        ports:
          - 5672:5672
          - 15672:15672
        options: >-
          --health-cmd="rabbitmq-diagnostics ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10
          
      kafka:
        image: confluentinc/cp-kafka:7.8.0
        ports:
          - 9092:9092
        env:
          KAFKA_NODE_ID: 1
          KAFKA_PROCESS_ROLES: broker,controller
          KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
          KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
          KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
          CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
          KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.422

      - name: Start Pulsar
        run: |
          docker run -d \
            --name pulsar \
            -p 6650:6650 \
            -p 8080:8080 \
            apachepulsar/pulsar:4.2.2 \
            bin/pulsar standalone

      - name: Start Mongo
        run: |
          docker run -d --name mongodb \
            -p 27017:27017 \
            mongo:8.3.4 --replSet rs0 --bind_ip_all
          
          sleep 5
          docker logs mongodb

      - name: Init Mongo Replica Set
        run: |
          docker exec mongodb mongosh --eval "rs.initiate({_id: 'rs0', members: [{_id: 0, host: '127.0.0.1:27017'}]})"

      - name: Wait Mongo Replica Set
        run: |
          for i in $(seq 1 30); do
            if docker exec mongodb mongosh --quiet --eval "rs.status().ok" | grep -q 1; then
              echo "MongoDB Replica Set is ready!"
              exit 0
            fi
            echo "Waiting for MongoDB... ($i)"
            sleep 2
          done
          echo "MongoDB failed to start in time."
          exit 1

      - name: Wait Pulsar
        run: |
          for i in $(seq 1 60); do
            curl -fs http://localhost:8080/admin/v2/clusters >/dev/null && exit 0
            sleep 2
          done
          docker logs pulsar
          exit 1



      - name: Wait Redis
        run: |
          for i in $(seq 1 60); do
            nc -z localhost 6379 && echo "Redis port open" && break
            sleep 1
          done
          
      - name: Wait MySql
        run: |
          echo "Waiting MySQL..."
          for i in $(seq 1 60); do
            nc -z localhost 3306 && break
            sleep 1
          done
          
      - name: Wait Kafka
        run: |
          echo "Waiting Kafka..."
          for i in $(seq 1 60); do
            nc -z localhost 9092 && break
            sleep 1
          done

#      - name: Test
#        run: dotnet test ./src/Shashlik.EventBus.sln
#        env:
#          DOTNET_ENVIRONMENT: GitHub